<p>Welcome to "kao Instagram"!</p>


<a href="/login">Sign in</a>

<br>
<br>

<a href="/registration">Registration</a>

<br>
<br>

<button id="img">Count images</button>

<script>
    $("#img").on('click', function () {
        var imgDiv = document.getElementById('number');
        imgDiv.removeChild(imgDiv.firstChild);

        $.ajax('/index/count', {
                success: function (data, status, xhr) {
                    $('#number').html(data);
                }
            });
    })
</script>

<div id="number">

</div>




