<p>Welcome to "kao Instagram"!</p>

<form action="/login">
    <button>Sign In</button>
</form>

<br>

<form action="/registration">
    <button>Sign Up</button>
</form>

<br>

<button id="img">Count images</button>

<script>
    $("#img").on('click', function () {
        var imgDiv = document.getElementById('number');
        imgDiv.removeChild(imgDiv.firstChild);

        $.ajax('/index/count', {
                success: function (data, status, xhr) {
                    $('#number').append(data);
                }
            });
    })
</script>

<div id="number">

</div>




