<form method="post" action="/login/signout">
    <input type="submit" name="signOutButton" value="Sign Out">
</form>

<br>
<form method="post" enctype="multipart/form-data" action="/profile/uploadImage">
    <input type="file" name="file">
    <button type="submit" name="uploadImage">Upload image</button>
</form>

<ul>
    <li>
        <a href='/profile'>Management</a>
    </li>
    <li>
        <a href='/settings'>My account</a>
    </li>
</ul>

<!--<div class="container">
    <div class="row">
        <div class="col-sm">
            One of three columns
        </div>
        <div class="col-sm">
            One of three columns
        </div>
        <div class="col-sm">
            One of three columns
        </div>
    </div>
</div>-->

<form method="POST" action="/profile/deleteImg">
    <?php $index = 0;
    foreach ($imageName as $img) {
        echo '<div style="float: left; padding: 0.07%">';
        echo '<p><img style="width: 470px; height: 470px;"src="img/'.$imageName[$index].'">'; echo '<br>';
        echo $homeMessage[$index];
        if($session === $homeMessage[$index]) {?>
            <button type="submit" name="name" value="<?php echo $imageName[$index] ?>">Delete</button>
    <?php };
         $index = $index + 1;
        echo '</div>';
    }; ?></p></form>


<?php
$numOfCols = 4;
$rowCount = 0;
?>
<div class="container">
    <div class="row">
    <?php
    foreach ($imageName as $row){
        ?>
        <div class="col-md-3">
                <img src="img/<?php echo $imageName[$rowCount]; ?>">
            </div>
        <?php
        $rowCount++;
        if($rowCount % $numOfCols == 0) echo '</div></div><div class="container"><div class="row">';
    }
    ?>