<form method="post" action="/login/signout">
    <input type="submit" name="signOutButton" value="Sign Out">
</form>

<br>
<form method="post" enctype="multipart/form-data" action="/profile/uploadImage">
    <input type="file" name="file">
    <button type="submit" name="uploadImage">Upload image</button>
</form>

<br>

<a href='/profile'>Management</a>
<br>
<br>
<a href='/settings'>My account</a>



<form method="POST" action="/profile/deleteImg">
    <?php $index = 0;
    foreach ($imageName as $img) {
        echo '<div style="float: left; padding: 0.07%">';
        echo '<p><img style="width: 470px; height: 470px;"src="img/'.$imageName[$index].'">'; echo '<br>';
        echo $homeMessage[$index];
        if($session === $homeMessage[$index]) {?>
            <button type="submit" name="name" value="<?php echo $imageName[$index] ?>">Delete</button>
    <?php };
         $index = $index + 1;
        echo '</div>';
    }; ?></p></form>