<form method="post" action="/login/signout">
    <input type="submit" name="signOutButton" value="Sign Out">
</form>

<br>
<form method="post" enctype="multipart/form-data" action="/profile/uploadImage">
    <input type="file" name="file">
    <button type="submit" name="uploadImage">Upload image</button>
</form>

<ul>
    <li>
        <a href='/profile'>Management</a>
    </li>
    <li>
        <a href='/settings'>My account</a>
    </li>
</ul>

<link rel='stylesheet' href='style.css'>

<from method="POST" action="/profile/deleteImg">
    <?php $index = 0;
    foreach ($imageName as $img) {
        echo '<p><img src="img/'.$imageName[$index].'" height="400" width="400">'; echo '<br>';
        echo $homeMessage[$index];
        if($session === $homeMessage[$index]) {
            echo '<button type="submit" name="name" value="<?php echo $homeMessage[$index] ?>">Delete</button>'; ?>


        <?php } ; $index = $index + 1;
        }; ?></p></form>

