<p>Welcome to registration form!</p>

<form method="post" action="/registration/signup">
    Username:<br>
    <input type="text" name="username"><br>
    Email:<br>
    <input type="text" name="email"><br>
    Password:<br>
    <input type="password" name="password"><br>
    Repeat password:<br>
    <input type="password" name="repeatPassword"><br>
    <input type="submit" name="signUpButton" value="Sign Up">
    <br>
    <br>
    <a href="/login">Go to login</a><br>
    <a href="/">Go to welcome page</a>
</form>