<p><?php echo $homeMessage ?></p>

<form method="post" action="settings/changePassword">
    Password:<br>
    <input type="text" name="password"><br><br>
    <input type="submit" name="changePassword" value="Change password">
</form>
<br>
<form method="post" action="settings/changeStatus">
    <p>Your profile is <?php echo $status ?></p>
    <input type="submit" name="changeStatus" value="Change status">
</form>
<br>
<form method="post" action="settings/deleteUserAccount">
    <input type="submit" name="removeAccount" value="Remove account">
</form>

<ul>
    <li>
        <a href='/profile'>Management</a>
    </li>
    <li>
        <a href='/settings'>My account</a>
    </li>
</ul>